export const LIST_TODO_ITEMS_REQUEST = "LIST_TODO_ITEMS_REQUEST "
export const LIST_TODO_ITEMS_SUCCESS = "LIST_TODO_ITEMS_SUCCESS "
export const LIST_TODO_ITEMS_FAIL = "LIST_TODO_ITEMS_FAIL "


export const ADD_TODO_ITEM = "ADD_TODO_ITEM"
export const REMOVE_TODO_ITEM = "REMOVE_TODO_ITEM"
export const COMPLETE_TODO_ITEM = "COMPLETE_TODO_ITEM"
